site_name: ProSeka DN42
site_description: Documentation for ProSeka DN42 Network
copyright: "© ProSeka DN42"

theme:
  name: material
  logo: site_arts/dn42.png
  favicon: site_arts/favicon.ico
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - obsidian-bridge
  - search
  - section-index
  - social:
      cards_layout_dir: layouts
      cards_layout: custom

  
site_url: "https://docs.proseka.darrenmc.dev"


markdown_extensions:
 - obsidian_media_mkdocs
 - obsidian_callouts
 - pymdownx.escapeall:
        hardbreak: true
